networks:
    1panel-network:
        external: true
services:
    localmosdns:
        container_name: mosdns
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: irinesistiana/mosdns:v4.5.3
        networks:
            - 1panel-network
        ports:
            - 5553:53/udp
            - 5553:53/tcp
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mosdns:/etc/mosdns
            - ./mosdns-x-linux-amd64/mosdns:/usr/bin/mosdns



